version: '3.9'

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=colkie
    ports:
      - '5432:5432'
    volumes:
      - ./database/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    command: [ "postgres", "-c", "log_statement=all" ]
  nestjs_app:
    build: .
    image: colkie-api
    platform: linux/amd64
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/colkie
    depends_on:
      - postgres